### ISSUE TITLE
Cannot build a new oracle db

### ISSUE THREAD

**Issue by jpahullo** [moodlehq/moodle-db-oracle#10]
Hi! I'm facing troubles trying to [add oracle support to moodle-plugin-ci](https://github.com/moodlehq/moodle-plugin-ci/issues/128). Now, I'm trying to build locally a moodle instance and oracle db cannot be set up.

Moodle branch: master, up-to-date
moodle-docker: master, up-to-date
Oracle db
PHP version: 7.4

The moodledocker_db_1 container shows these logs:

```bash
$ docker logs -f moodledocker_db_1 
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.

ERROR:
ORA-12547: TNS:lost contact


SP2-0306: Invalid option.
Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
ERROR:
ORA-12547: TNS:lost contact


SP2-0306: Invalid option.
Usage: CONN[ECT] [{logon|/|proxy} [AS {SYSDBA|SYSOPER|SYSASM}] [edition=value]]
where <logon> ::= <username>[/<password>][@<connect_identifier>]
      <proxy> ::= <proxyuser>[<username>][/<password>][@<connect_identifier>]
Shutting down Oracle Database 11g Express Edition instance.
Stopping Oracle Net Listener.

Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.

/usr/sbin/startup.sh: running /docker-entrypoint-initdb.d/01-moodle-user.sql

SQL*Plus: Release 11.2.0.2.0 Production on Thu Aug 12 09:48:47 2021

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

ERROR:
ORA-12547: TNS:lost contact


Enter user-name: Enter password: 
ERROR:
ORA-12547: TNS:lost contact


Enter user-name: 


```

These logs comes from the startup.sh script.

I removed locally my docker images and rebuilt it with no success.

From the oracle container, I try loging in via sqlplus command and there is no login possible.

Any idea why?

**Comment by jpahullo** [comment]
I'm using the image id (from docker images):

moodlehq/moodle-db-oracle-r2 latest cbccc731cb4a 7 months ago 2.1GB

I removed the docker image and pulled again just today.

**Comment by stronk7** [comment]
Hi @jpahullo ,

did you manage to fix the problem? I use these images locally a lot, so I can perform any Oracle test in my dev environment...  and haven't faced any problem like that. Last time, today.

Ciao :-)

**Comment by jpahullo** [comment]
Hi!

I had to move to do other tasks without finishing this issue. Sorry.

I'm deciding to close this issue and open again another one if necessary. Just for cleaning it up.

Thanks for your time.

Jordi

**Comment by stronk7** [comment]
Thanks Jordi!
